services:
  db:
    image: mysql:8

    ports: 
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - app_data:/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
volumes:
  mysql:
  app_data: